services:
  # traefik:
  #   image: traefik
  #   container_name: traefik
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.email=your@email.com"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "3030:3030" # Dashboard
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./letsencrypt:/letsencrypt
  #   networks:
  #     - helm-network

  oci-storage:
    image: fizzbuzz2/oci-storage:latest
    build:
      context: .
    container_name: oci-storage
    volumes:
      - ./charts:/app/data # Pour persister les charts
      - ./src/config:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helm.rule=Host(`helm.your-domain.com`)"
      - "traefik.http.routers.helm.entrypoints=websecure"
      - "traefik.http.routers.helm.tls.certresolver=myresolver"
      - "traefik.http.services.helm.loadbalancer.server.port=3030"
    networks:
      - helm-network
    ports:
      - "3030:3030"

networks:
  helm-network:
    driver: bridge
