apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: {{ $.Release.Name | quote }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  rules:
  - host: {{ $.Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
              name:  {{ $.Values.service.name }}
              port:
                number: {{ $.Values.service.port }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $.Values.ingress.host }}
    secretName: {{ $.Values.ingress.tls.secretName | default (printf "%s-certificate-tls" $.Release.Name) }}
{{- end }}
