apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-portal-test-app
  namespace: kube-infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: testing-apps
  source:
    chart: helm-portal-test-app
    repoURL: helm-portal.dc-tech.work
    targetRevision: 1.0.2  # Using flat name until charts/ namespace is fixed
    helm:
      releaseName: helm-portal-test-app
      values: |
        replicaCount: 1
        imagePullSecrets:
          - name: helm-portal-registry
        image:
          repository: helm-portal.dc-tech.work/images/test-app
          tag: "1.0.1"
          pullPolicy: Always
        nodeSelector:
          kubernetes.io/hostname: zima
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-portal-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
