apiVersion: "v2"
name: "oci-storage"
version: 1.3.0
appVersion: "1.1.0"
description: Host all your charts in your cluster
type: application
icon: https://avatars.githubusercontent.com/u/12622760?v=4
maintainers:
  - name: didlawowo
    email: chris@dc-consulting.pro
