root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ./cmd/server/"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "data"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  exclude_regex = ["_test.go", "index\\.yaml"]